import type { ContentItem } from "./content";

const now = new Date().toISOString();
type SeedItem = Omit<ContentItem, "source_region"> & { source_region?: string };

export const curatedSeedItems: SeedItem[] = [
  {
    id: "seed-cdc-autism",
    source_name: "CDC",
    source_type: "official",
    source_url: "https://www.cdc.gov/autism/",
    canonical_url: "https://www.cdc.gov/autism/",
    title_original: "Autism Spectrum Disorder",
    title_zh: "自闭症谱系障碍资源总览",
    summary_original:
      "CDC provides overview information on autism, screening, diagnosis, early signs, and family support resources.",
    summary_zh: "CDC 提供关于自闭症的总体介绍、筛查、诊断、早期信号与家庭支持资源。",
    excerpt: "Overview information on autism, screening, diagnosis, early signs, and family support resources.",
    language: "bilingual",
    published_at: "2025-09-12T00:00:00.000Z",
    content_type: "guide",
    topics: ["自闭症", "家庭支持", "政策与服务"],
    audiences: ["family", "clinician"],
    conditions: ["autism"],
    review_status: "approved",
    review_notes: "优先展示给家长与支持人员。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      tags: ["screening", "support"],
    },
  },
  {
    id: "seed-nimh-adhd",
    source_name: "NIMH",
    source_type: "official",
    source_url: "https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd",
    canonical_url: "https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd",
    title_original: "Attention-Deficit/Hyperactivity Disorder",
    title_zh: "ADHD 官方主题页",
    summary_original:
      "NIMH explains ADHD symptoms, diagnosis, treatment options, and practical questions families can discuss with clinicians.",
    summary_zh: "NIMH 解释 ADHD 的症状、诊断、治疗选择，以及家庭可与临床人员讨论的实际问题。",
    excerpt: "NIMH explains ADHD symptoms, diagnosis, treatment options, and practical questions for families.",
    language: "bilingual",
    published_at: "2025-10-01T00:00:00.000Z",
    content_type: "guide",
    topics: ["ADHD", "家庭支持", "政策与服务"],
    audiences: ["family", "clinician", "self-advocate"],
    conditions: ["adhd"],
    review_status: "approved",
    review_notes: "官方权威来源。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      tags: ["diagnosis", "treatment"],
    },
  },
  {
    id: "seed-understood-learning",
    source_name: "Understood",
    source_type: "media",
    source_url: "https://www.understood.org/",
    canonical_url: "https://www.understood.org/",
    title_original: "How to support kids with learning and thinking differences in school",
    title_zh: "如何在学校支持有学习与思维差异的孩子",
    summary_original:
      "A practical primer on school accommodations, communication with teachers, and building student confidence.",
    summary_zh: "面向家长和教师的实用入门，涵盖学校支持、与老师沟通和建立孩子自信。",
    excerpt: "A practical primer on school accommodations, teacher communication, and student confidence.",
    language: "bilingual",
    published_at: "2025-06-21T00:00:00.000Z",
    content_type: "news",
    topics: ["学习困难", "教育", "家庭支持"],
    audiences: ["family", "educator"],
    conditions: ["learning-difficulties"],
    review_status: "approved",
    review_notes: "优质媒体内容，适合大众入口。",
    ingested_at: now,
    metadata: {
      credibility: "medium",
      tags: ["school accommodations"],
    },
  },
  {
    id: "seed-nice-adhd",
    source_name: "NICE",
    source_type: "official",
    source_url:
      "https://www.nice.org.uk/guidance/ng87",
    canonical_url:
      "https://www.nice.org.uk/guidance/ng87",
    title_original: "Attention deficit hyperactivity disorder: diagnosis and management",
    title_zh: "NICE ADHD 诊断与管理指南",
    summary_original:
      "NICE guideline covering assessment, diagnosis, treatment, and support pathways for ADHD across age groups.",
    summary_zh: "NICE 指南覆盖 ADHD 的评估、诊断、治疗与支持路径，适合需要循证建议的读者。",
    excerpt: "Guideline covering assessment, diagnosis, treatment, and support pathways for ADHD across age groups.",
    language: "bilingual",
    published_at: "2025-09-15T00:00:00.000Z",
    content_type: "guide",
    topics: ["ADHD", "政策与服务", "教育"],
    audiences: ["clinician", "educator", "family"],
    conditions: ["adhd"],
    review_status: "approved",
    review_notes: "高权威临床指南。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      tags: ["guideline", "diagnosis", "management"],
    },
  },
  {
    id: "seed-nhs-autism",
    source_name: "NHS",
    source_type: "official",
    source_url: "https://www.nhs.uk/conditions/autism/",
    canonical_url: "https://www.nhs.uk/conditions/autism/",
    title_original: "Autism",
    title_zh: "NHS 自闭症总览",
    summary_original:
      "NHS explains what autism is, getting diagnosed, support options, and advice for adults, parents and carers.",
    summary_zh: "NHS 提供自闭症介绍、诊断路径、支持选择，以及面向成人、家长与照护者的建议。",
    excerpt: "NHS explains autism, diagnosis routes, support options, and advice for adults, parents and carers.",
    language: "bilingual",
    published_at: "2025-08-22T00:00:00.000Z",
    content_type: "guide",
    topics: ["自闭症", "政策与服务", "家庭支持"],
    audiences: ["family", "self-advocate"],
    conditions: ["autism"],
    review_status: "approved",
    review_notes: "适合普通读者的权威入口。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      tags: ["diagnosis", "support"],
    },
  },
  {
    id: "seed-chadd-school",
    source_name: "CHADD",
    source_type: "official",
    source_url: "https://chadd.org/for-parents/school-accommodations-and-adhd/",
    canonical_url: "https://chadd.org/for-parents/school-accommodations-and-adhd/",
    title_original: "School accommodations and ADHD",
    title_zh: "学校支持与 ADHD",
    summary_original:
      "CHADD outlines how families can work with schools on accommodations, classroom supports, and communication plans.",
    summary_zh: "CHADD 介绍家长如何与学校协作，推进课堂支持、合理便利与沟通计划。",
    excerpt: "How families can work with schools on accommodations, classroom supports, and communication plans.",
    language: "bilingual",
    published_at: "2025-07-18T00:00:00.000Z",
    content_type: "guide",
    topics: ["ADHD", "教育", "家庭支持"],
    audiences: ["family", "educator"],
    conditions: ["adhd"],
    review_status: "approved",
    review_notes: "学校场景实用性强。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      tags: ["school", "accommodations"],
    },
  },
  {
    id: "seed-ncld-overview",
    source_name: "NCLD",
    source_type: "official",
    source_url: "https://www.ncld.org/learning-disability-101/what-is-a-learning-disability/",
    canonical_url: "https://www.ncld.org/learning-disability-101/what-is-a-learning-disability/",
    title_original: "What Is a Learning Disability?",
    title_zh: "什么是学习困难？",
    summary_original:
      "NCLD provides an accessible explanation of learning disabilities, school impact, and family advocacy basics.",
    summary_zh: "NCLD 用易懂语言解释学习困难的概念、学校影响以及家庭倡导的基础做法。",
    excerpt: "An accessible explanation of learning disabilities, school impact, and family advocacy basics.",
    language: "bilingual",
    published_at: "2025-05-30T00:00:00.000Z",
    content_type: "guide",
    topics: ["学习困难", "教育", "家庭支持"],
    audiences: ["family", "educator"],
    conditions: ["learning-difficulties"],
    review_status: "approved",
    review_notes: "学习困难主题核心入口。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      tags: ["overview", "advocacy"],
    },
  },
  {
    id: "seed-autistica-work",
    source_name: "Autistica",
    source_type: "official",
    source_url: "https://www.autistica.org.uk/what-is-autism/employment",
    canonical_url: "https://www.autistica.org.uk/what-is-autism/employment",
    title_original: "Autism and employment",
    title_zh: "自闭症与就业",
    summary_original:
      "Autistica highlights common workplace barriers, practical supports, and why employment policy matters for autistic adults.",
    summary_zh: "Autistica 介绍自闭症成人在职场中的常见障碍、可行支持以及就业政策的重要性。",
    excerpt: "Common workplace barriers, practical supports, and why employment policy matters for autistic adults.",
    language: "bilingual",
    published_at: "2025-04-12T00:00:00.000Z",
    content_type: "guide",
    topics: ["自闭症", "职场", "政策与服务"],
    audiences: ["self-advocate", "employer", "researcher"],
    conditions: ["autism"],
    review_status: "approved",
    review_notes: "补足成人职场场景。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      tags: ["employment", "adults"],
    },
  },
  {
    id: "seed-pubmed-review",
    source_name: "PubMed",
    source_type: "academic",
    source_url: "https://pubmed.ncbi.nlm.nih.gov/39123456/",
    canonical_url: "https://pubmed.ncbi.nlm.nih.gov/39123456/",
    title_original: "Neurodiversity-affirming practices in education: a scoping review",
    title_zh: "教育中的神经多样性肯定式实践：范围综述",
    summary_original:
      "A research-oriented entry summarizing recent review evidence on inclusive teaching, accommodations, and student wellbeing.",
    summary_zh: "面向研究与教育工作者的论文入口，聚焦包容教学、合理便利和学生福祉的近期综述证据。",
    excerpt: "Recent review evidence on inclusive teaching, accommodations, and student wellbeing.",
    language: "en",
    published_at: "2025-03-10T00:00:00.000Z",
    content_type: "review",
    topics: ["神经多样性", "教育"],
    audiences: ["researcher", "educator"],
    conditions: ["neurodiversity"],
    review_status: "approved",
    review_notes: "研究入口示例。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      pmid: "39123456",
      tags: ["review", "education"],
    },
  },
];

export const incomingSeedItems: SeedItem[] = [
  {
    id: "incoming-workplace-guide",
    source_name: "ACAS",
    source_type: "official",
    source_url: "https://www.acas.org.uk/",
    canonical_url: "https://www.acas.org.uk/",
    title_original: "Making your organisation more ADHD-inclusive",
    title_zh: "让组织对 ADHD 更友好的职场实践",
    summary_original:
      "A practical draft item on workplace adjustments, manager communication, and reducing unnecessary barriers for ADHD staff.",
    summary_zh: "关于职场调整、管理沟通和减少不必要障碍的待审条目。",
    excerpt: "A practical draft item on workplace adjustments, manager communication, and reducing unnecessary barriers for ADHD staff.",
    language: "bilingual",
    published_at: "2026-01-16T00:00:00.000Z",
    content_type: "guide",
    topics: ["ADHD", "职场"],
    audiences: ["employer", "self-advocate"],
    conditions: ["adhd"],
    review_status: "approved",
    review_notes: "自动发布：官方来源。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      tags: ["workplace adjustments"],
    },
  },
  {
    id: "incoming-neurodiversity-review",
    source_name: "Journal of Autism and Developmental Disorders",
    source_type: "academic",
    source_url: "https://pubmed.ncbi.nlm.nih.gov/00000000/",
    canonical_url: "https://pubmed.ncbi.nlm.nih.gov/00000000/",
    title_original: "Neurodiversity-affirming support in higher education: a review",
    title_zh: "高校中的神经多样性肯定式支持：综述",
    summary_original:
      "Review article candidate covering accommodation design, stigma reduction, and student-led support in higher education.",
    summary_zh: "聚焦高校支持设计、污名减少和学生主导支持的综述型条目。",
    excerpt: "Review article candidate covering accommodation design, stigma reduction, and student-led support in higher education.",
    language: "en",
    published_at: "2025-11-08T00:00:00.000Z",
    content_type: "review",
    topics: ["神经多样性", "教育"],
    audiences: ["educator", "researcher"],
    conditions: ["neurodiversity"],
    review_status: "approved",
    review_notes: "自动发布：研究综述入口。",
    ingested_at: now,
    metadata: {
      credibility: "high",
      tags: ["higher education", "review"],
    },
  },
  {
    id: "incoming-understood-executive",
    source_name: "Understood",
    source_type: "media",
    source_url: "https://www.understood.org/en/articles/executive-function-101",
    canonical_url: "https://www.understood.org/en/articles/executive-function-101",
    title_original: "Executive function 101",
    title_zh: "执行功能入门",
    summary_original:
      "A practical introduction to executive function challenges and support strategies across school and home settings.",
    summary_zh: "介绍执行功能困难及其在学校和家庭中的支持策略。",
    excerpt: "A practical introduction to executive function challenges and support strategies across school and home settings.",
    language: "bilingual",
    published_at: "2025-02-14T00:00:00.000Z",
    content_type: "guide",
    topics: ["学习困难", "教育", "家庭支持"],
    audiences: ["family", "educator"],
    conditions: ["learning-difficulties", "adhd"],
    review_status: "approved",
    review_notes: "自动发布：大众实用资源。",
    ingested_at: now,
    metadata: {
      credibility: "medium",
      tags: ["executive function"],
    },
  },
];
